### ISSUE TITLE
Preview option is not available

### ISSUE THREAD

**Issue by akostylev-quantium** [viacheslav-lozinskyi/Preview-CSV#1]
After I installed Preview-CSV extension:
![image](https://user-images.githubusercontent.com/101227728/160731967-a03cdea3-25d6-4263-902f-448b0458cbdb.png)

I don't see a preview button for some reason:
![image](https://user-images.githubusercontent.com/101227728/160731991-29bc964f-7797-4069-b2e1-adb850375491.png)

Microsoft Visual Studio Community 2022
Version 17.1.2
VisualStudio.17.Release/17.1.2+32319.34
Microsoft .NET Framework
Version 4.8.04161

**Comment by viacheslav-lozinskyi** [comment]
Preview-CSV it's extension to [MetaOutput](https://marketplace.visualstudio.com/items?itemName=ViacheslavLozinskyi.MetaOutput-2022) and it works only with this installed extension.

For Visual Studio 2017, 2019 - MetaOutput installed automatically together with Preview-CSV.
For Visual Studio 2022 - MetaOutput necessary to install manually.

Please take a look is this extnsion installed?

**Comment by akostylev-quantium** [comment]
Thanks, Viacheslav. No, MetaOutput is not installed. I think it will be easier for me to use VSCode with a simple CSV extension. No worries

**Comment by viacheslav-lozinskyi** [comment]
I plan to implement MetaOutput for VSCode, but it require big efforts, and therefore it is posponed at this moment.
